#!/bin/bash
# Compare strategy parameters before and after improvements

echo "═══════════════════════════════════════════════════════════"
echo "STRATEGY PARAMETER COMPARISON"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Parameter                 | BEFORE  | AFTER   | Change"
echo "─────────────────────────────────────────────────────────"
echo "RSI Oversold (LONG)       | <30     | <35     | +5 (more signals)"
echo "RSI Overbought (SHORT)    | >70     | >65     | -5 (more signals)"
echo "BB Lower (LONG)           | <20%    | <30%    | +10% (more signals)"
echo "BB Upper (SHORT)          | >80%    | >70%    | -10% (more signals)"
echo "Min Score Threshold       | 75/110  | 70/110  | -5 (more signals)"
echo "Max Hold Time             | 5 min   | 15 min  | +10 min (better exits)"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "EXPECTED IMPACT:"
echo "  • Signal frequency: 1-2/week → 3-5/day (5-10x increase)"
echo "  • Entry quality: Still high (70/110 = 64% threshold)"
echo "  • Trade development: Better (15min vs 5min)"
echo "  • Win rate needed: ~55% (vs 60% before)"
echo ""
echo "UNCHANGED (Still Conservative):"
echo "  • 1h trend filter: MANDATORY (prevents counter-trend)"
echo "  • Spread: ≤0.05% (tight spreads only)"
echo "  • Volume: $5M+ (high liquidity only)"
echo "  • Order book: $50K+ depth (good execution)"
echo "  • Stop/Target: 0.5%/1.0% (1.8:1 R/R after costs)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "TESTING RECOMMENDATION:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Run bot for 24-48 hours"
echo "2. Monitor signal frequency (expect 3-5/day)"
echo "3. Check signal quality (scores should be 70-90)"
echo "4. Track win rate (target 55%+)"
echo ""
echo "If too many signals: Increase min score to 72-73"
echo "If too few signals: Further relax RSI to 40/60"
echo ""
echo "═══════════════════════════════════════════════════════════"
